@startuml
!pragma layout smetana
!include _estilo.iuml
hide empty description
title CU-15 Consultar Profesor
state "Cargando" as Carga
Carga : entry / findActiveProfessors() : List<Professor>
state "Lista mostrada" as Lista
Lista : entry / tableView.getItems().setAll(professors)
state "Error" as Error
Error : entry / showAlert("Error", ERROR)
[*] --> Carga
Carga --> Lista : [hay registros]
Carga --> Error : [ServiceException / ValidationException]
Lista --> [*]
Error --> [*]
@enduml
